"""Chapter writing to various formats."""

import subprocess
import tempfile
from pathlib import Path

from ..core.logging import get_logger
from .models import Chapter

logger = get_logger("chapter_writer")


class ChapterWriter:
    """Writes chapter markers to files in various formats."""

    def write_to_m4b(self, m4b_path: Path, chapters: list[Chapter]) -> bool:
        """Write chapter metadata into an M4B file using ffmpeg."""
        if not chapters:
            return False

        metadata_content = self._build_ffmetadata(chapters)

        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".txt", delete=False
        ) as f:
            metadata_file = Path(f.name)
            f.write(metadata_content)

        temp_output = m4b_path.with_suffix(".tmp.m4b")

        try:
            cmd = [
                "ffmpeg",
                "-i",
                str(m4b_path),
                "-i",
                str(metadata_file),
                "-map_metadata",
                "1",
                "-c",
                "copy",
                "-y",
                str(temp_output),
            ]

            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)

            if result.returncode == 0:
                m4b_path.unlink()
                temp_output.rename(m4b_path)
                return True

            if temp_output.exists():
                temp_output.unlink()
            return False

        except (subprocess.TimeoutExpired, FileNotFoundError) as e:
            logger.warning(f"Failed to write chapters to M4B: {e}")
            if temp_output.exists():
                temp_output.unlink()
            return False
        finally:
            if metadata_file.exists():
                metadata_file.unlink()

    def write_to_ffmetadata(
        self, output_path: Path, chapters: list[Chapter]
    ) -> bool:
        """Write chapters as FFMETADATA1 format file."""
        if not chapters:
            return False

        content = self._build_ffmetadata(chapters)

        try:
            output_path.write_text(content, encoding="utf-8")
            return True
        except OSError as e:
            logger.warning(f"Failed to write ffmetadata file: {e}")
            return False

    def write_to_cue(self, output_path: Path, chapters: list[Chapter]) -> bool:
        """Write chapters as a .cue sidecar file."""
        if not chapters:
            return False

        lines = ['REM COMMENT "Generated by BookBot"']
        lines.append('FILE "audio.m4b" M4A')

        for i, chapter in enumerate(chapters, 1):
            lines.append(f"  TRACK {i:02d} AUDIO")
            lines.append(f'    TITLE "{chapter.title}"')

            total_seconds = chapter.start_ms / 1000.0
            minutes = int(total_seconds // 60)
            seconds = int(total_seconds % 60)
            frames = int((total_seconds % 1) * 75)
            lines.append(f"    INDEX 01 {minutes:02d}:{seconds:02d}:{frames:02d}")

        try:
            output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            return True
        except OSError as e:
            logger.warning(f"Failed to write cue file: {e}")
            return False

    def _build_ffmetadata(self, chapters: list[Chapter]) -> str:
        """Build FFMETADATA1 content string."""
        lines = [";FFMETADATA1"]

        for chapter in chapters:
            lines.append("")
            lines.append("[CHAPTER]")
            lines.append("TIMEBASE=1/1000")
            lines.append(f"START={chapter.start_ms}")
            if chapter.end_ms is not None:
                lines.append(f"END={chapter.end_ms}")
            lines.append(f"title={chapter.title}")

        return "\n".join(lines) + "\n"
